import java.awt.Font;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;
import java.time.Instant;
import java.util.Random;

/**
 * @brief this is Corb's/Aurora's Lib file for the easy access globals and the like
 */
public class CorbLib {

  /* ======================================================================== */
  /* --------------------------- lib stubs ---------------------------------- */
  /* ======================================================================== */

  /**
   * @brief called by the Main.main(String[]) and just handles some on run stuffs
   * @param args
   */
  public static void corblibmain(String[] args){
    loadCourFont();

    setupUntrackedRandomisation();
  }

  /* ======================================================================== */
  /* ------------------------------------------------------------------------ */
  /* ======================================================================== */


  /* ======================================================================== */
  /* ------------------------------ Tile stuffs ----------------------------- */
  /* ======================================================================== */

  public static char getDefault_MapCellType() {
    return '#';
  }
  public static char getDefault_tileByRoomType(char type) {
    return getDefault_MapCellType();
  }
  
  // TODO: need to port the type listing to here

  /* ======================================================================== */
  /* ------------------------------------------------------------------------ */
  /* ======================================================================== */



  /* ======================================================================== */
  /* ----------------- untracked randomisation ------------------------------ */
  /* ======================================================================== */

  /** 
   * @brief used for generating the untracked seed/rng/random generations
   * @warning dont use this for anything you want to reproduce later,
   *            this is spookie
   */
  private static Random untrackedRandomSeed;
  /**
   * @brief purely for generation of random numbers that arent needing to be predetermined values at all
   *        as they will be untracked and purely random
   */
  private static void setupUntrackedRandomisation() {
    // generate it by the time
    untrackedRandomSeed = new Random(getSeedLong());
  }
  /**
   * @brief produces a 'long' that can be used to seed a rng seed
   * @return 'long' generated by current epoch seconds long seed
   */
  private static long getSeedLong() {
    // make a random roller based off epoch time
    Random rand = new Random(Instant.now().getEpochSecond());
    // return the next rolled random long
    return rand.nextLong();
  }
  public static long getUntrackedRandomLong(){
    return untrackedRandomSeed.nextLong();
  }
  public static long getUntrackedRandomLong(long bound){
    return untrackedRandomSeed.nextLong(bound);
  }
  public static int getUntrackedRandomInt(){
    return untrackedRandomSeed.nextInt();
  }
  public static int getUntrackedRandomInt(int bound){
    return untrackedRandomSeed.nextInt(bound);
  }
  
  /* ======================================================================== */
  /* ------------------------------------------------------------------------ */
  /* ======================================================================== */


  /* ======================================================================== */
  /* ----------------------- font stuffs ------------------------------------ */
  /* ======================================================================== */
  /**
   * @brief tries to load in our courier font
   */
  public static void loadCourFont(){
    try{
      GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
      File cour = new File("game/data/cour.ttf");
      ge.registerFont(Font.createFont(Font.TRUETYPE_FONT, cour));
    } catch(IOException e){
      System.err.println("cant load cour.ttf properly in path 'game/data/cour.ttf'");
    } catch(Exception e){
      System.err.println("large scoped exception catcher for CorbLib.loadCourFont()" );
    }
  }
  /* ======================================================================== */
  /* ------------------------------------------------------------------------ */
  /* ======================================================================== */














}
